In [1]:
import pandas as pd
data = pd.read_csv("./MoviewReviews.csv")

In [2]:
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
data.isnull().sum()

review       0
sentiment    0
dtype: int64

In [4]:
data.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [6]:
# Step 3: Convert sentiment labels into numbers
# positive = 1 , negative = 0

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
data['sentiment'] = encoder.fit_transform(data['sentiment'])

In [7]:
# View updated data
data.head()

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [8]:
# Step 4: Separate input and output

X = data['review']
y = data['sentiment']

In [10]:
# Step 5: Split dataset into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [11]:
# Step 6: Convert text reviews into numerical vectors using TF-IDF

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words='english'
)

X_train = tfidf.fit_transform(X_train).toarray()
X_test = tfidf.transform(X_test).toarray()

In [12]:
# Step 7: Import Deep Learning libraries

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
# Step 8: Build Deep Neural Network model

model = Sequential()

# Input + Hidden Layer 1
model.add(Dense(128, activation='relu', input_shape=(5000,)))

# Hidden Layer 2
model.add(Dense(64, activation='relu'))

# Output Layer
model.add(Dense(1, activation='sigmoid'))

# View model summary
model.summary()

C:\Users\saksh\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 128)                 │         640,128 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              65 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 648,449 (2.47 MB)

 Trainable params: 648,449 (2.47 MB)

 Non-trainable params: 0 (0.00 B)

In [14]:
# Step 9: Compile the model

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [15]:
# Step 10: Train the model

history = model.fit(
    X_train,
    y_train,
    epochs=5,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/5
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.8156 - loss: 0.3990 - val_accuracy: 0.8790 - val_loss: 0.2884
Epoch 2/5
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.9159 - loss: 0.2120 - val_accuracy: 0.8733 - val_loss: 0.2980
Epoch 3/5
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.9385 - loss: 0.1611 - val_accuracy: 0.8734 - val_loss: 0.3453
Epoch 4/5
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.9762 - loss: 0.0697 - val_accuracy: 0.8684 - val_loss: 0.4594
Epoch 5/5
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.9930 - loss: 0.0199 - val_accuracy: 0.8656 - val_loss: 0.6535

In [20]:
# Step 11: Evaluate model on test data

loss, accuracy = model.evaluate(X_test, y_test)

print("Loss:", loss)
print("Accuracy:", accuracy)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8677 - loss: 0.6202
Loss: 0.6331561803817749
Accuracy: 0.8655999898910522

In [17]:
# Step 12: Predict sentiment for test reviews

predictions = model.predict(X_test)

# Convert probabilities into 0 or 1
predictions = (predictions > 0.5).astype(int)

print(predictions[:10])

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]]

In [18]:
# Step 13: Classification Report

from sklearn.metrics import classification_report

print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.87      0.86      0.86      4961
           1       0.87      0.87      0.87      5039

    accuracy                           0.87     10000
   macro avg       0.87      0.87      0.87     10000
weighted avg       0.87      0.87      0.87     10000

In [19]:
# Step 14: Predict custom review

review = ["This movie was amazing and very emotional"]

# Convert review into TF-IDF vector
review_vector = tfidf.transform(review).toarray()

# Predict
prediction = model.predict(review_vector)

if prediction > 0.5:
    print("Positive Review")
else:
    print("Negative Review")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
Positive Review